### ISSUE TITLE
Allow to configure the writer to something other than stdout

### ISSUE THREAD

**Issue by lowlighter** [deno-library/progress#30]
It seems like currently it's hardcoded to stdout:
https://github.com/deno-library/progress/blob/bcc5d0dd12577d5c5c6babe5cc1854d930fae2b0/mod.ts#L57

But it'd be nice to be able to set it to stderr too

The reasoning is that for cli, it's not uncommon to depends on stdout returns when using the shell syntax (like `$()`), but currently this messes the output
```bash
deno --allow-run=$(deno task install-and-return-path) run mod.ts
```

Kind similar behavior like curl/wget uses for progress bar.
Actually it may be a better default to use stderr, but it may be a breaking change

**Comment by fuxingZhang** [comment]
Today I'm going to release a new version to support stderr.
I'd also be more than happy to merge your pull request.

**Comment by fuxingZhang** [comment]
Landed on v1.5.0

https://github.com/deno-library/progress/blob/45e626d5d04b3c65096c332e0c5da342b0d2931b/examples/stderr.ts#L9

**Comment by fuxingZhang** [comment]
Initially, I was using `writeAllSync`, but on December 27, 2023, I discovered that `writeAllSync` was deprecated, and the documentation recommended using the `stream API`. 
> https://deno.land/std@0.202.0/streams/write_all.ts?s=writeAll

>(will be removed after 1.0.0) Use WritableStream, ReadableStream.from, and pipeTo() 

As a result, I released version 1.4.1 (Remove deprecated writeAllSync, Use WritableStream instead). 

However, today I found that both `writeAll` and `writeAllSync` are now available again. I checked the source code and issues, and found:
> https://github.com/denoland/std/issues/4120
> https://github.com/denoland/std/pull/4128

I believe `writeAll` is simpler. Therefore, I changed `Deno.stdout.writable.getWriter()` to `writeAll`. Since I am currently using the promise style, so I changed to use `writeAll`. 

Loaded on `v1.5.1`.

**Comment by fuxingZhang** [comment]
I forgot to change the version in the deno.json, so I force pushed the changes again, and it's working fine now.

**Comment by lowlighter** [comment]
Nice ! Thanks a lot for being so quick !

**Comment by lowlighter** [comment]
Works as expected, thanks again !
